// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ0ZFl6cXbyNMREcSmdp6g38aXGTWPKV8',
    appId: '1:140221921230:web:e0e9a98a06d45139c61d9f',
    messagingSenderId: '140221921230',
    projectId: 'beemo-app',
    authDomain: 'beemo-app.firebaseapp.com',
    storageBucket: 'beemo-app.appspot.com',
    measurementId: 'G-G0CHY618EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgp1PZ1JcOMJMDoolJOx8U0YlLJ5QHK3A',
    appId: '1:140221921230:android:df3e321f18ef222ec61d9f',
    messagingSenderId: '140221921230',
    projectId: 'beemo-app',
    storageBucket: 'beemo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGg5FWRuuZOiGijDFnXywKwMN7XF9KeiY',
    appId: '1:140221921230:ios:b99f600df4b4dccdc61d9f',
    messagingSenderId: '140221921230',
    projectId: 'beemo-app',
    storageBucket: 'beemo-app.appspot.com',
    iosClientId: '140221921230-aenkt31jmh165932v03v6g44fvqmjhr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.beemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGg5FWRuuZOiGijDFnXywKwMN7XF9KeiY',
    appId: '1:140221921230:ios:b99f600df4b4dccdc61d9f',
    messagingSenderId: '140221921230',
    projectId: 'beemo-app',
    storageBucket: 'beemo-app.appspot.com',
    iosClientId: '140221921230-aenkt31jmh165932v03v6g44fvqmjhr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.beemo',
  );
}
